name: Deploy Bot and Services

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env file for deployment
        run: |
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env
          echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> .env
          echo "ALLOWED_TELEGRAM_IDS=${{ secrets.ALLOWED_TELEGRAM_IDS }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "METABASE_URL=${{ secrets.METABASE_URL }}" >> .env
          echo "METABASE_DOMAIN=${{ secrets.METABASE_DOMAIN }}" >> .env
          echo "CERTBOT_EMAIL=${{ secrets.CERTBOT_EMAIL }}" >> .env
          echo "MB_DB_TYPE=postgres" >> .env
          echo "MB_DB_HOST=db" >> .env
          echo "MB_DB_PORT=5432" >> .env
          echo "MB_DB_DBNAME=${{ secrets.POSTGRES_DB }}" >> .env
          echo "MB_DB_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "MB_DB_PASS=${{ secrets.POSTGRES_PASSWORD }}" >> .env

      - name: Replace Metabase domain in Nginx config
        run: |
          METABASE_DOMAIN_VALUE="${{ secrets.METABASE_DOMAIN }}"
          ESCAPED_METABASE_DOMAIN=$(echo "$METABASE_DOMAIN_VALUE" | sed 's/\./\\./g')
          sed -i "s|server_name \\${METABASE_DOMAIN};|server_name $ESCAPED_METABASE_DOMAIN;|g" ./nginx/conf.d/metabase.conf
          sed -i "s|ssl_certificate /etc/nginx/ssl/\\${METABASE_DOMAIN}/fullchain.pem;|ssl_certificate /etc/nginx/ssl/$ESCAPED_METABASE_DOMAIN/fullchain.pem;|g" ./nginx/conf.d/metabase.conf
          sed -i "s|ssl_certificate_key /etc/nginx/ssl/\\${METABASE_DOMAIN}/privkey.pem;|ssl_certificate_key /etc/nginx/ssl/$ESCAPED_METABASE_DOMAIN/privkey.pem;|g" ./nginx/conf.d/metabase.conf
          
          echo "Nginx config updated with actual domain."

      - name: Copy files to server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Переменная для пути к проекту на сервере
            PROJECT_DIR="/home/${{ secrets.SSH_USER }}/fin_bot_project"

            mkdir -p $PROJECT_DIR
            rsync -az --delete-before ${{ github.workspace }}/ $PROJECT_DIR/
            cd $PROJECT_DIR

            docker compose down --remove-orphans
            docker compose pull
            docker compose up --build -d db metabase bot nginx certbot

            sleep 10

            docker compose restart nginx

            echo "Deployment complete!"